
/*日程表 */
CREATE TABLE IF NOT EXISTS GTD_SCHEDULE
(
	ID BIGINT NOT NULL COMMENT 'Id，主键',
	ITEM_HOPE_DONE_DATE INT COMMENT '事项期望完成日期，yyyyMMdd',
	ITEM_CONTENT VARCHAR(1024) NOT NULL COMMENT '事项内容',
	ITEM_TYPE VARCHAR(32) COMMENT '任务类型',
	ITEM_CLASS INT COMMENT '事项类型',
	ITEM_FONT_COLOR VARCHAR(32) COMMENT '任务字体颜色，RGB值',
	ITEM_ICON VARCHAR(512) COMMENT '任务图标',
	ITEM_LINK VARCHAR(512) COMMENT '任务相关链接，网址',
	ITEM_REMARKS VARCHAR(4096) COMMENT '备注',
	ITEM_STATUS INT DEFAULT 0 NOT NULL COMMENT '任务状态。0-进行中；100-按时完成；200-过期未完成；300-过期已完成；400-草稿；500-不用再做',
	ITEM_REAL_DONE_DATE INT COMMENT '事项实际完成日期，yyyyMMdd',
	CREATE_TIME DATETIME DEFAULT NOW() NOT NULL COMMENT '创建时间',
	UPDATE_TIME DATETIME DEFAULT NOW() NOT NULL COMMENT '修改时间',
	PRIMARY KEY (ID)
) COMMENT='日程表';